# TagPlugin // Version 1.0 // Made by zDr4l #
# Welcome to my first ever real plugin project! Find more information about this here: https://github.com/Dr4l/TagPlugin


# tag_message: This option sets the message displayed to a player when they get tagged.
# You can customize the message using color codes and placeholders.
# In this example, the message is "&cYou got tagged!" which will appear in red color.
tag_message: "&cYou got tagged!"

# tagger_message: This option sets the message displayed to a player when they successfully tag another player. Similar to the previous option, you can use color codes and placeholders.
# The placeholder "{tagged}" will be replaced with the name of the player who got tagged.
# In this example, the message is "&aYou tagged {tagged}!" which will appear in green color.
tagger_message: "&aYou tagged {tagged}!"

# console_message: This option sets the message displayed in the server console when a player successfully tags another player.
# It uses placeholders to represent the names of the tagger and tagged players.
# In this example, the message is "&7{tagger} tagged {tagged}!" which will appear in light gray color.
console_message: "&7{tagger} tagged {tagged}!"

#global_message: This option sets the message displayed to all other players on the server when a player successfully tags another player.
#Like the previous options, it supports placeholders for the tagger and tagged players. In this example, the message is "&6{tagger} tagged {tagged}!" which will appear in gold color.
global_message: "&6{tagger} tagged {tagged}!"


tag_cooldown: 30

game_start_message: "&aThe tag game has started!"

