name: TagPlugin
main: com.example.tagplugin.TagPlugin
version: 1.0
api-version: 1.19
commands:
  starttag:
    description: Start the tag game
    usage: /starttag
    permission: tagplugin.start
  stoptag:
    description: Stop the tag game
    usage: /stoptag
    permission: tagplugin.stop
  leaderboard:
    description: Display the top 5 (if there are 5) most tagged players
    usage: /leaderboard
